
server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  client:
    service-url:
      defaultZon: http://localhost:8761/eureka




